### ISSUE TITLE
Appointment Scheduler - Udemy Course Project

### ISSUE THREAD

**Issue by abdulislamian** [aeongt710/dotnet-roadmap#10]
https://github.com/abdulislamian/AppointmentScheduler
Appointment Scheduler : 15/09/2023
**Status** - _Inprogress_

**Comment by ShakeelAbbasKhan** [comment]
https://github.com/ShakeelAbbasKhan/AppointmentScheduler.git
Appointment Scheduler
Status - InProgress

**Comment by CodingArc4** [comment]
https://github.com/CodingArc4/AppointmentSchedulingApp

**Comment by tariqafridi1** [comment]
https://github.com/tariqafridi1/AppointmentScheduling
Tariq
Remarks: Appointment In progress

**Comment by tariqafridi1** [comment]
https://github.com/tariqafridi1/AppointmentScheduling
Identity Management Completed

**Comment by muqddas** [comment]
https://github.com/muqddas/Appointments-Scheduler
Muqaddas Fatima
Status = In progress

**Comment by tariqafridi1** [comment]
https://github.com/tariqafridi1/AppointmentScheduling

Status: Completed
