### ISSUE TITLE
BakeryShop -Udemy Project ( Practice )

### ISSUE THREAD

**Issue by abdulislamian** [aeongt710/dotnet-roadmap#12]
https://github.com/abdulislamian/BakeryShop
Status - _InProgress_
Date : **26/09/2023**

**Comment by ShakeelAbbasKhan** [comment]
https://github.com/ShakeelAbbasKhan/PieShop.git
Status - InProgress

**Comment by CodingArc4** [comment]
https://github.com/CodingArc4/BethanysPieShop

Status: In Progress
