### ISSUE TITLE
Azure Deployment (Appointment Scheduler)

### ISSUE THREAD

**Issue by abdulislamian** [aeongt710/dotnet-roadmap#13]
Working and Overview of Azure Resources, SQL Server, App Services..
Project Deployment Link : **_https://jmm.azurewebsites.net/_**

**Comment by ShakeelAbbasKhan** [comment]
Create a account a Azure. Deploy Project on Azure and deal with azure errors
https://appointmentscheduler1.azurewebsites.net/

**Comment by CodingArc4** [comment]
https://appointmentschedulingapp.azurewebsites.net/

app wroking an published on azure
