### ISSUE TITLE
Revise DotNet Core Concepts (CodeWithMosh)

### ISSUE THREAD

**Issue by abdulislamian** [aeongt710/dotnet-roadmap#14]
https://github.com/abdulislamian/CodeWithMosh
Status : **_InProgress_**

**Comment by ShakeelAbbasKhan** [comment]
https://github.com/ShakeelAbbasKhan/VidlyTaskWithMosh.git
Status - InProgress

**Comment by CodingArc4** [comment]
https://github.com/CodingArc4/VidlyInDotnet7
Status - InProgress
