### ISSUE TITLE
Task 1: Custom Validation Attribute

### ISSUE THREAD

**Issue by aeongt710** [aeongt710/dotnet-roadmap#15]
You have to create a Validation attribute to validate a file such that the file has anyone of the extension from the specified extensions and size limit, it can also support multiples files or restrict it to only having specified no of files

**Comment by tariqafridi1** [comment]
https://github.com/tariqafridi1/CustomValidationAttribute
Tariq
Status: Completed.
Today Task : Custom Validation Attribute #15.
Goodluck......

**Comment by muqddas** [comment]
Muqaddas Fatima
https://github.com/muqddas/fileProcessing

**Comment by abdulislamian** [comment]
https://github.com/abdulislamian/ImageUpload

Abdullah

**Comment by CodingArc4** [comment]
https://github.com/CodingArc4/FileValidationTask

Munib Khan

**Comment by ShakeelAbbasKhan** [comment]
https://github.com/ShakeelAbbasKhan/ImageUpload.git   // validationAttribute
https://github.com/ShakeelAbbasKhan/TaskValidateFile.git   // simple
