### ISSUE TITLE
Interceptor Filter and Data Binding

### ISSUE THREAD

**Issue by aeongt710** [aeongt710/dotnet-roadmap#16]
# Interceptor Filter and Data Binding

### Overview
This repository provides solutions for two primary tasks:

1. **Interceptor Filter for Outgoing Responses**: A middleware to inspect and modify outgoing responses from action methods.
2. **Data Binding using jQuery**: Binding data from multiple request data sources into an input object in various action methods.

### Interceptor Filter for Outgoing Responses

- **Objective**: Intercept outgoing response from an action and append specific details in the response headers.
  - Action Name
  - HTTP Method
  - HTTP Scheme
  - Host
  - Port
  - Time taken to execute
  - Server date and time

### Data Binding using jQuery

- **Objective**: Create multiple action methods and bind data from different request data sources into an input object using jQuery.

**Comment by ShakeelAbbasKhan** [comment]
https://github.com/ShakeelAbbasKhan/InterceptorFilterDataBinding.git

**Comment by CodingArc4** [comment]
https://github.com/CodingArc4/MiddlewareTask

M.Munib Khan

**Comment by abdulislamian** [comment]
https://github.com/abdulislamian/Task02
Abdullah Khan

**Comment by muqddas** [comment]
https://github.com/muqddas/MiddleWare
Muqaddas Fatima
