### ISSUE TITLE
ASP.NET Identity Web Application

### ISSUE THREAD

**Issue by aeongt710** [aeongt710/dotnet-roadmap#17]
# ASP.NET Identity Web Application

This project is a simple web application implementing authentication and authorization using ASP.NET Identity. It is designed with custom identity management.

**Note**: Don't use default identity. All identity functionalities should be custom implemented.

## Features

The application includes the following functionalities:

- **User Management (CRUD)**
  - Create, Read, Update, and Delete users
  - Implementing features like Forgot Password and Reset Password
  - Ability to Assign Roles to users

- **Role Management (CRUD)**
  - Create, Read, Update, and Delete roles

- **Role-Based Authorization**
  - Implementing role-based authorization on endpoints
  - Ensuring a role can't be deleted as long as there are users associated with it

**Comment by abdulislamian** [comment]
#TaskThree : Custom Identity Implementation & Role Based Authorization
**_https://github.com/abdulislamian/CustomIdentity_**

**Comment by ShakeelAbbasKhan** [comment]
https://github.com/ShakeelAbbasKhan/IdentityTaskWebApp.git

**Comment by CodingArc4** [comment]
https://github.com/CodingArc4/Identity-Application-Assignment

**Comment by muqddas** [comment]
https://github.com/muqddas/IdentityImplimentation
