### ISSUE TITLE
Content Negotiation

### ISSUE THREAD

**Issue by aeongt710** [aeongt710/dotnet-roadmap#19]
## Content Negotiation

We are tasked with developing a server-side solution that ensures our web service dynamically adapts to the content negotiation requirements of incoming HTTP requests. The system must be capable of handling complex scenarios with the following specifications:

1. **Content Type Negotiation:** The system must parse the `Accept` header from incoming requests to determine the client's preferred response format. For example:
   - If the client requests `application/json`, the response should be in JSON format.
   - If `text/html` or `text/plain` is requested, the response should be in simple HTML or plain text, respectively.

2. **AJAX Request Handling:** It should detect whether the request is made via an AJAX call. The expected behavior in such cases is:
   - For AJAX requests, return a "partial view" suitable for updating the client's DOM without a full page reload.
   - For non-AJAX requests, return a "full view" which constitutes the entire HTML page.

3. **Graceful Fallback:** In cases where the `Accept` header is not present, or the specified content type is unsupported, the system should default to a predefined content type, ensuring the client receives an appropriate response.

4. **Performance Considerations:** The system should maintain performance efficiency, keeping the latency low and, where possible, leveraging caching mechanisms without compromising the dynamic nature of content negotiation.

### Goals

- Implement a robust content negotiation mechanism in ASP.NET Core that adheres to the HTTP protocol standards.
- Ensure that the mechanism gracefully handles multiple content types, AJAX requests, and fallback scenarios.
- Integrate this system with existing routing and view templating features provided by the ASP.NET Core framework.

### Requirements

- The solution must be developed using ASP.NET Core.
- It must comply with security best practices to avoid common vulnerabilities (e.g., sanitizing inputs).
- It should include error handling to manage unsupported content types and any other potential request anomalies.

**Comment by abdulislamian** [comment]
**_https://github.com/abdulislamian/ContentNegotiation_**

**Comment by CodingArc4** [comment]
https://github.com/CodingArc4/NegotiationTask

**Comment by ShakeelAbbasKhan** [comment]
https://github.com/ShakeelAbbasKhan/ContentNegotiation.git
