### ISSUE TITLE
Weather Console Application

### ISSUE THREAD

**Issue by aeongt710** [aeongt710/dotnet-roadmap#20]
# Weather Console Application

This repository contains a simple console application that fetches and displays weather forecast data from a public API in a formatted JSON structure.

## Description

The Weather Console Application is built using ASP.NET Core and makes use of the OpenWeatherMap API to retrieve weather forecast data for a specified location. The application presents the data in a readable format in the console.

## Features

- Fetches data from OpenWeatherMap API.
- Parses JSON response.
- Displays weather forecast in a user-friendly format.

### Prerequisites

To run this application, you will need:

- .NET 6.0 SDK or later
- An API key from OpenWeatherMap or any other

### Configuration

Update the `appsettings.json` with your OpenWeatherMap API key:

    {
      "WeatherApi": {
        "BaseUrl": "https://api.openweathermap.org/data/2.5/",
        "ApiKey": "YOUR_API_KEY"
      }
    }

## Usage

Upon running the application, you will be prompted to enter a location. Enter the city name and country code (optional) and press Enter. The application will display the weather forecast data for that location.

## Dependencies

- Microsoft.Extensions.DependencyInjection
- Microsoft.Extensions.Configuration
- Microsoft.Extensions.Configuration.Json
- System.Net.Http
- Newtonsoft.Json

**Comment by abdulislamian** [comment]
**_https://github.com/abdulislamian/WeatherConsole_**

**Comment by CodingArc4** [comment]
https://github.com/CodingArc4/WeatherConsoleTask

**Comment by ShakeelAbbasKhan** [comment]
https://github.com/ShakeelAbbasKhan/Weather.git
