### ISSUE TITLE
Library System Console Application

### ISSUE THREAD

**Issue by aeongt710** [aeongt710/dotnet-roadmap#8]
# Library System Console Application

This is an intermediate-level C# console application that simulates a Library System. It allows users to manage a library's collection of books and users.

## Task Description

You are tasked with building a Library System using C# and following object-oriented programming principles. The project involves creating dictionaries to manage books and users, implementing user-friendly interactions, and applying input validation. Here are the key components:

### Dictionaries

- `BooksDictionary`: A dictionary representing the library's collection of books. Each book is associated with its ISBN as the key and contains properties like Title, Author, and Availability status.

- `UsersDictionary`: A dictionary representing the library's users. Each user is associated with their Library Card ID as the key and contains properties like Name.

### User Interaction

- Users can:
  - View a list of available books.
  - Borrow a book by entering their Library Card ID and the book's ISBN.
  - Return a book using their Library Card ID and the book's ISBN.
  - Add new books to the `BooksDictionary` (admin function).

### OOP Principles

- Implement OOP principles like encapsulation, inheritance, and polymorphism as appropriate. Consider creating classes to represent books, users, and any other necessary entities.

### Input Validation

- Ensure that the program handles invalid inputs gracefully and validates user inputs to prevent errors.

### Persistence (Optional)

- Optionally, save the `BooksDictionary` and `UsersDictionary` to a file so that they can be loaded again when the program restarts.

## Usage

Provide instructions on how to run the Library System in your console application.

**Comment by Muqaddasfatima** [comment]
https://github.com/Muqaddasfatima/LIBRARY-SYS.git
MUQADDAS

**Comment by abdulislamian** [comment]
https://github.com/abdulislamian/AppointmentScheduler
**Appointment Scheduler :**    _15/09/2023_

**Comment by tariqafridi1** [comment]
https://github.com/tariqafridi1/LibraryConsoleAppTask
Tariq
