### ISSUE TITLE
Expense Tracker - Udemy Course Project

### ISSUE THREAD

**Issue by abdulislamian** [aeongt710/dotnet-roadmap#9]
https://github.com/abdulislamian/FinanceTracker
**Expense Tracker Project** - _Completed_

**Comment by ShakeelAbbasKhan** [comment]
https://github.com/ShakeelAbbasKhan/Expense.git
Expense Project Complete

**Comment by CodingArc4** [comment]
https://github.com/CodingArc4/UdemyCrudApp1
Munib khan
Status: Completed

**Comment by tariqafridi1** [comment]
https://github.com/tariqafridi1/ProjectJMM
Tariq 
Status: Progress

**Comment by tariqafridi1** [comment]
https://github.com/tariqafridi1/ProjectJMM
created Expense controller,views with server and client side validation

**Comment by tariqafridi1** [comment]
https://github.com/tariqafridi1/ProjectJMM/commit/7ae419a6b604d20981fe549f6f2096c5d6c9afdc
TARIQ
Remarks: Expense Tracker Completed

**Comment by muqddas** [comment]
https://github.com/muqddas/ExpenseTracker
Muqaddas Fatima 
status : Completed
